spring:
  application:
    name: users-svc
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10       # Max number of connections in the pool
      minimum-idle: 5             # Minimum number of idle connections
      idle-timeout: 600000        # 10 minutes before idle connection is closed
      max-lifetime: 1800000       # 30 minutes: recommended to avoid stale connections
      connection-timeout: 30000   # 30 seconds: wait max time to get a connection
      validation-timeout: 5000    # 5 seconds: max time to validate a connection
      pool-name: ScraperPool
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_svc


# Logging
logging:
  config: classpath:log4j2-local.xml


# Service Registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/