spring:
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients: whatsapp-svc
  application:
    name: remind-pack-users-svc
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}


srv:
  feign:
    names:
      whatsapp: whatsapp-svc

otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: console
  instrumentation:
    micrometer:
      enabled: true
    http:
      client:
        emit-experimental-telemetry: true
  propagators: "tracecontext,baggage,b3"


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
    propagation:
      produce: w3c,b3,b3_multi
      consume: w3c
